#initial the slave for ndb cluster
- name: Ensure group "mcc" exists
  group:
    name: mcc
    state: present

- name: Ensure the user "mcc" exists
  user:
    name: mcc
    group: mcc
    password: "{{ mcc_password | password_hash('sha512') }}"
    update_password: always

- name: Create directories for slave
  file: path={{ item }} state=directory owner=mcc group=mcc
  with_items:
    - "{{ package_dir }}"
    - "{{ shelldir }}"
    - "{{ monitordir }}"
    - "{{ basedir }}"
    - "{{ datadir }}"

- name: Rendering mysql parameter file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: mysql
    group: mysql
    mode: 0644
  with_items:
    - { src: 'my.cnf.j2', dest: "{{ basedir }}/my.cnf" }

- name: Rendering bash file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0744
  with_items:
    - { src: 'my.cnf_auto.sh.j2', dest: "{{ basedir }}/my.cnf_auto.sh" }
    - { src: 'see_log.sh.j2', dest: "{{ shelldir }}/see_log.sh" }

- name: Auto config my.cnf
  shell: "sh -x {{ basedir }}/my.cnf_auto.sh"

- name: Remove my.cnf_auto.sh
  file:
    path: "{{ basedir }}/my.cnf_auto.sh"
    state: absent
    remote_src: yes

- name: Install the ndb cluster repo
  yum:
    name: "{{ remote_repo }}"
    state: present

- name: Copy the mysql-community.repo
  copy: src=mysql-community.repo dest=/etc/yum.repos.d/mysql-community.repo

- name: Install the ndb cluster basic rpm
  yum:
    name: ["{{ cluster_server_name }}", "{{ cluster_lib_compat_name }}"]
    state: present
  register: result
  retries: 7
  until: result is succeeded

- name: Start mysql server
  systemd:
    name: mysqld
    state: started

- name: Enable mysql server
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Obtain root password tempory
  shell: "grep -i root@localhost: /var/log/mysqld.log | awk '{ print $13 }'"
  register: root_password_temp

- name: Modify root password
  mysql_user:
    login_user: root
    login_password: "{{ root_password_temp.stdout }}"
    name: root
    password: "{{ root_password }}"
    update_password: always
    login_port: "{{ mysql_port }}"
    priv: '*.*:ALL,GRANT'
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present

- name: Config replication for ndb
  mysql_replication:
    login_port: "{{ mysql_port }}"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    mode: changemaster
    master_host: "{{ master_host }}"
    master_port: "{{ mysql_port }}"
    master_user: repl
    master_password: "{{ mysql_monitor_password }}"
    master_auto_position: no
    master_log_file: binlog.000001
    master_log_pos: 156

- name: Start slave status for slaves
  mysql_replication:
    login_port: "{{ mysql_port }}"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    mode: startslave