# 系统环境检测，排除干扰

- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no

- name: 永久关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: Uninstall mariadb
  yum:
    name: mariadb
    state: absent

- name: Install base packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: Disable kernel hugepage
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled;echo never > /sys/kernel/mm/transparent_hugepage/defrag"

- name: Disable swap
  sysctl:
    name: vm.swappiness
    value: '0'
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: yes

- name: Disable file system atime
  mount:
    path: "{{ install_dir }}"
    src: "{{ fstab_src }}"
    fstype: ext4
    opts: noatime
    state: present
    backup: yes

- name: Remount file path
  mount:
    path: "{{ install_dir }}"
    src: "{{ fstab_src }}"
    fstype: ext4
    opts: noatime
    state: remounted

- name: Uninstall mysql
  yum:
    name: mysql-cluster*
    state: absent
  when: whether_uninstall

- name: Remove existing mcc directory
  file:
    path: "{{ install_dir }}"
    state: absent
    remote_src: 'True'
  when: whether_uninstall

#- name: 更新所有软件包
#  yum:
#    name: '*'
#    state: latest