# 系统环境检测，排除干扰

- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no

- name: 永久关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: Uninstall mariadb
  yum:
    name: mariadb
    state: absent

- name: Install base packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: Stop mysql server via systemctl
  systemd:
    name: mysqld
    state: stopped
  when: whether_uninstall

- name: Stop mysql server via mysqladmin
  shell: "mysqladmin -uroot -h127.0.0.1 shutdown"
  when: whether_uninstall

- name: Stop ndb_mgm
  shell: " ndb_mgm -e shutdown"
  when: whether_uninstall and (ansible_hostname == "ansible")

- name: Uninstall mysql
  yum:
    name: mysql*
    state: absent
  when: whether_uninstall

- name: Remove existing mcc directory
  file:
    path: "{{ basedir }}"
    state: absent
    remote_src: 'True'
  when: whether_uninstall

#- name: 更新所有软件包
#  yum:
#    name: '*'
#    state: latest