
- name: Backp deploy.js and parameters.js
  copy:
    src: "{{ item }}"
    dest: "{{ shelldir }}"
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
    backup: no
  with_items:
    - /usr/share/mysql-8.0/mcc/frontend/js/mcc/configuration/deploy.js
    - /usr/share/mysql-8.0/mcc/frontend/js/mcc/configuration/parameters.js
  when: inventory_hostname_short in groups.mcc_slave_{{ env }}

- name: Upgrade the mysql-cluster*
  yum:
    name: mysql-cluster*
    state: latest
  register: result
  retries: 7
  until: result is succeeded

- name: Copy back deploy.js and parameters.js
  copy:
    src: "{{ item }}"
    dest: "/usr/share/mysql-8.0/mcc/frontend/js/mcc/configuration"
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
    backup: no
  with_items:
    - "{{ shelldir }}/deploy.js"
    - "{{ shelldir }}/parameters.js"
  when: inventory_hostname_short in groups.mcc_slave_{{ env }}